In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fetal-health-classification/fetal_health.csv


In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/kaggle/input/fetal-health-classification/fetal_health.csv')

In [4]:
df.columns

Index(['baseline value', 'accelerations', 'fetal_movement',
       'uterine_contractions', 'light_decelerations', 'severe_decelerations',
       'prolongued_decelerations', 'abnormal_short_term_variability',
       'mean_value_of_short_term_variability',
       'percentage_of_time_with_abnormal_long_term_variability',
       'mean_value_of_long_term_variability', 'histogram_width',
       'histogram_min', 'histogram_max', 'histogram_number_of_peaks',
       'histogram_number_of_zeroes', 'histogram_mode', 'histogram_mean',
       'histogram_median', 'histogram_variance', 'histogram_tendency',
       'fetal_health'],
      dtype='object')

In [5]:
df=df.drop('severe_decelerations',axis=1)

WE DROPPED THIS COLUMN OF 'severe_decelerations' beacause all of its value=0 so its has no role in this model ( I already knew it beacuse I have done EDA in the model where I wrote NN from scratch, so I am using that knowledge here)

In [6]:
df.columns,df.shape

(Index(['baseline value', 'accelerations', 'fetal_movement',
        'uterine_contractions', 'light_decelerations',
        'prolongued_decelerations', 'abnormal_short_term_variability',
        'mean_value_of_short_term_variability',
        'percentage_of_time_with_abnormal_long_term_variability',
        'mean_value_of_long_term_variability', 'histogram_width',
        'histogram_min', 'histogram_max', 'histogram_number_of_peaks',
        'histogram_number_of_zeroes', 'histogram_mode', 'histogram_mean',
        'histogram_median', 'histogram_variance', 'histogram_tendency',
        'fetal_health'],
       dtype='object'),
 (2126, 21))

In [7]:
X=df.drop('fetal_health',axis=1)

In [8]:
Y=df['fetal_health']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
X_train,X_val,Y_train,Y_val=train_test_split(X_train,Y_train,test_size=0.2,random_state=42)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [10]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(1360, 20) (426, 20) (1360,) (426,)


In [11]:
X.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  prolongued_decelerations  \
0                0.000                       0.0   
1                0.003                       0.0   
2                0.003                       0.0   
3                0.003                       0.0   
4                0.000                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  \
0                                               43.0        
1                                                0.0        
2                                                0.0        
3                                                0.0        
4                                                0.0        

   mean_value_of_long_term_variability  histogram_width  histogram_min  \
0                                  2.4             64.0           62.0   
1                                 10.4            130.0           68.0   
2                                 13.4            130.0           68.0   
3                                 23.0            117.0           53.0   
4                                 19.9            117.0           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  
0                 1.0  
1                 0.0  
2                 0.0  
3                 1.0  
4                 1.0

In [12]:
Y.head(),Y_train.head(),Y_test.head()

(0    2.0
 1    1.0
 2    1.0
 3    1.0
 4    1.0
 Name: fetal_health, dtype: float64,
 1603    1.0
 1840    1.0
 1008    1.0
 2084    1.0
 909     1.0
 Name: fetal_health, dtype: float64,
 282     1.0
 1999    1.0
 1709    1.0
 988     1.0
 2018    1.0
 Name: fetal_health, dtype: float64)

In [13]:
import tensorflow as tf
from tensorflow import keras

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

In [14]:
Y_train=keras.utils.to_categorical(Y_train)
Y_test=keras.utils.to_categorical(Y_test)
Y_val=keras.utils.to_categorical(Y_val)

In [15]:
Y_test[0],Y_train[0],Y_val[0]

(array([0., 1., 0., 0.], dtype=float32),
 array([0., 1., 0., 0.], dtype=float32),
 array([0., 1., 0., 0.], dtype=float32))

ARCHITECTURE

In [16]:
model = keras.Sequential(
[
    keras.layers.Dense(128,activation='relu',input_shape=(20,)),
    keras.layers.Dense(256,activation='relu'),
    keras.layers.Dense(4,activation='softmax'),
]
)
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               2688      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 4)                 1028      
                                                                 
Total params: 36,740
Trainable params: 36,740
Non-trainable params: 0
_________________________________________________________________


COMPILATION OF THE MODEL 

In [17]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

TRAINING THE MODEL AND VALIDATING USING THE VALIDATION DATA

In [18]:
model.fit(X_train,Y_train,batch_size=32,epochs=20, validation_data=(X_val,Y_val))

Epoch 1/20
43/43 [==============================] - 1s 9ms/step - loss: 2.6847 - accuracy: 0.7426 - val_loss: 0.6028 - val_accuracy: 0.8000
Epoch 2/20
43/43 [==============================] - 0s 3ms/step - loss: 0.5930 - accuracy: 0.8331 - val_loss: 0.5177 - val_accuracy: 0.8559
Epoch 3/20
43/43 [==============================] - 0s 3ms/step - loss: 0.5982 - accuracy: 0.8346 - val_loss: 0.4743 - val_accuracy: 0.8735
Epoch 4/20
43/43 [==============================] - 0s 3ms/step - loss: 0.7162 - accuracy: 0.8250 - val_loss: 0.9362 - val_accuracy: 0.6794
Epoch 5/20
43/43 [==============================] - 0s 3ms/step - loss: 0.5779 - accuracy: 0.8382 - val_loss: 0.7473 - val_accuracy: 0.8471
Epoch 6/20
43/43 [==============================] - 0s 3ms/step - loss: 0.4913 - accuracy: 0.8390 - val_loss: 0.6419 - val_accuracy: 0.8471
Epoch 7/20
43/43 [==============================] - 0s 3ms/step - loss: 0.7357 - accuracy: 0.8007 - val_loss: 0.5464 - val_accuracy: 0.8382
Epoch 8/20
43/43 [==

WE HAVE A MODEL WITH 85% ACCURACY ON TRAINING DATA

In [19]:
test_loss,test_acc=model.evaluate(X_test,Y_test)
print(f'Test loss:{test_loss}')
print(f'Test accuracy: {test_acc}')

14/14 [==============================] - 0s 2ms/step - loss: 0.4182 - accuracy: 0.8803
Test loss:0.41821375489234924
Test accuracy: 0.8802816867828369


WE HAVE ~88% ACCURACY ON TESTING DATA. 